Repository 1chipML/1chipML, pull requests merged in 2023-04, with the labels that each got.

#43 Added prototype section to readme
  README.md
Labels: documentation

#35 Shortest path in a graph
  prototype/mc_shortest_path/README.md
  prototype/mc_shortest_path/arduino_mc_shortest_path/arduino_mc_shortest_path.ino
  prototype/mc_shortest_path/arduino_mc_shortest_path/arduino_serial_port.cpp
  prototype/mc_shortest_path/arduino_mc_shortest_path/arduino_serial_port.hpp
  prototype/mc_shortest_path/arduino_mc_shortest_path/linear_congruential_random_generator.c
  prototype/mc_shortest_path/arduino_mc_shortest_path/linear_congruential_random_generator.h
  prototype/mc_shortest_path/arduino_mc_shortest_path/mc_shortest_path.py
  prototype/mc_shortest_path/arduino_mc_shortest_path/monte_carlo.c
  prototype/mc_shortest_path/arduino_mc_shortest_path/monte_carlo.h
  src/monte_carlo.c
  src/monte_carlo.h
  tests/test_monte_carlo.c
Labels: enhancement

#39 Elite value optimization
  prototype/genetic_curve_fitting/genetic_curve_fitting.ino
  prototype/genetic_curve_fitting/genetic_curve_fitting.py
  src/genetic.c
  src/genetic.h
  tests/test_genetic.c
Labels: enhancement

#40 Added implementation of LU decomposition
  Makefile
  doc/1chipML_manual.tex
  src/1chipml.h
  src/lu_decomposition.c
  src/lu_decomposition.h
  tests/test_lu_decomposition.c
Labels: documentation, enhancement

#42 Lu prototype
  prototype/large_scale_recommender/README.md
  prototype/large_scale_recommender/large_scale_recommender.py
  prototype/large_scale_recommender/large_scale_recommender/arduino_serial_port.cpp
  prototype/large_scale_recommender/large_scale_recommender/arduino_serial_port.hpp
  prototype/large_scale_recommender/large_scale_recommender/finite_difference.c
  prototype/large_scale_recommender/large_scale_recommender/finite_difference.h
  prototype/large_scale_recommender/large_scale_recommender/gradient_descent.c
  prototype/large_scale_recommender/large_scale_recommender/gradient_descent.h
  prototype/large_scale_recommender/large_scale_recommender/large_scale_recommender.ino
  prototype/large_scale_recommender/large_scale_recommender/linear_congruential_random_generator.c
  prototype/large_scale_recommender/large_scale_recommender/linear_congruential_random_generator.h
  prototype/large_scale_recommender/large_scale_recommender/lu_decomposition.c
  prototype/large_scale_recommender/large_scale_recommender/lu_decomposition.h
  prototype/large_scale_recommender/large_scale_recommender/matrix.c
  prototype/large_scale_recommender/large_scale_recommender/matrix.h
  prototype/large_scale_recommender/serial_port.py
  src/lu_decomposition.h
Labels: enhancement

#45 Whole graph traversal
  prototype/mc_shortest_path/arduino_mc_shortest_path/arduino_mc_shortest_path.ino
  prototype/mc_shortest_path/arduino_mc_shortest_path/mc_shortest_path.py
Labels: enhancement

#46 Saved latex pipeline
  .github/workflows/LatexPipeline.tar
  .github/workflows/README.md
  doc/1chipML_logo.eps
Labels: documentation
