Repository 1chipML/1chipML, pull requests merged in 2023-02, with the labels that each got.

#14 Fixed permission issues with file test_poly_interpolation.c
  Makefile
  src/poly_interpolation.c
  src/poly_interpolation.h
  tests/test_poly_interpolation.c
Labels: bug

#16 Given command to make tests was invalid in README.md
  README.md
Labels: documentation

#13 Formatted source code under the LLVM format (#29)
  src/1chipml.h
  src/gauss_elimination.c
  src/gauss_elimination.h
  src/linear_congruential_random_generator.c
  src/linear_congruential_random_generator.h
  src/mc_integration.c
  src/mc_std.c
  src/mc_stratified_sampling.c
  src/poly_interpolation.c
  src/poly_interpolation.h
  tests/test_gauss_elimination.c
  tests/test_linear_congruential_random_generator.c
  tests/test_poly_interpolation.c
Labels: enhancement

#17 Removed cpp headers and added their equivalent in c
  src/mc_integration.c
  src/mc_std.c
  src/mc_stratified_sampling.c
Labels: enhancement

#15 Added variables for the Makefile rules
  .gitignore
  Makefile
Labels: enhancement

#18 FFT and DFT implementation
  Makefile
  doc/1chipML_manual.pdf
  doc/1chipML_manual.tex
  src/1chipml.h
  src/DFT.c
  src/DFT.h
  src/FFT.c
  src/FFT.h
  tests/test_DFT.c
  tests/test_FFT.c
Labels: documentation, enhancement

#19 Implemented Lanczos Algorithm
  Makefile
  doc/1chipML_manual.pdf
  doc/1chipML_manual.tex
  src/lanczos.c
  src/lanczos.h
  tests/test_lanczos.c
Labels: documentation, enhancement
